import type { Metadata } from "next";

import { ToolPageLayout } from "../components/ToolPageLayout";
import { PaybackPeriodCalculatorForm } from "./PaybackPeriodCalculatorForm";

export const metadata: Metadata = {
  title: "Free Payback Period Calculator | CAC Payback",
  description:
    "Calculate customer acquisition payback period from CAC, monthly revenue, gross margin, and variable costs. See monthly contribution and recovery time.",
  openGraph: {
    title: "Free Payback Period Calculator | CAC Payback",
    description: "Estimate how many months customer contribution takes to recover acquisition cost.",
    type: "website",
    url: "https://rybbit.com/tools/payback-period-calculator",
    siteName: "Rybbit",
  },
  twitter: {
    card: "summary_large_image",
    title: "Free Payback Period Calculator | CAC Payback",
    description: "Estimate CAC payback from monthly revenue, margin, and customer-level costs.",
  },
  alternates: { canonical: "https://rybbit.com/tools/payback-period-calculator" },
};

const faqs = [
  {
    question: "How is CAC payback period calculated?",
    answer:
      "Divide customer acquisition cost by the monthly contribution generated by one customer. Monthly contribution is monthly revenue multiplied by gross margin, minus any additional per-customer variable costs not already included in the margin.",
  },
  {
    question: "Should I use revenue or gross profit?",
    answer:
      "Use gross profit or contribution, not revenue alone. Product delivery and service costs reduce the amount available to recover acquisition spend. Using revenue alone makes payback appear faster than it is unless gross margin is effectively 100%.",
  },
  {
    question: "What if monthly contribution is zero or negative?",
    answer:
      "The acquisition cost cannot be recovered under those inputs, so the simple payback period is undefined. Review price, gross margin, usage-related costs, or the acquisition cost assumptions before relying on a payback target.",
  },
  {
    question: "Does this calculator account for churn?",
    answer:
      "No. This simple calculator assumes the customer remains active and contributes the same amount each month. For cohort planning, compare the estimated payback period with retention and model churn, expansion, discounts, and payment timing separately.",
  },
  {
    question: "What is a good CAC payback period?",
    answer:
      "A workable target depends on cash availability, gross margin, contract terms, retention, and growth strategy. Compare payback with your own cash cycle and customer lifetime rather than using one benchmark for every business.",
  },
  {
    question: "How can Rybbit improve the inputs?",
    answer:
      "Rybbit can help measure conversion volume, acquisition paths, and retention behavior. Combine that behavioral data with accounting and ad-cost data to estimate CAC and contribution using the same customer cohort and period.",
  },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebApplication",
      name: "Payback Period Calculator",
      description: "A free calculator for customer acquisition cost payback period.",
      url: "https://rybbit.com/tools/payback-period-calculator",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Any",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      author: { "@type": "Organization", name: "Rybbit", url: "https://rybbit.com" },
    },
    {
      "@type": "FAQPage",
      mainEntity: faqs.map(faq => ({
        "@type": "Question",
        name: faq.question,
        acceptedAnswer: { "@type": "Answer", text: faq.answer },
      })),
    },
  ],
};

const educationalContent = (
  <>
    <h2>What is customer acquisition payback period?</h2>
    <p>
      CAC payback period estimates how long one customer's contribution takes to recover the cost of acquiring that
      customer. It connects acquisition efficiency with cash flow: the longer recovery takes, the longer acquisition
      spending remains tied up before it can fund more growth.
    </p>

    <h2>Payback period formula</h2>
    <p>
      Use <code>payback months = CAC ÷ monthly customer contribution</code>. Monthly contribution is usually monthly
      recurring revenue multiplied by gross margin, minus other variable customer costs that are not already included in
      cost of service.
    </p>
    <p>
      If CAC is $600, monthly revenue is $120, and gross margin is 80%, monthly gross profit is $96. With no additional
      variable cost, estimated payback is 6.25 months.
    </p>

    <h2>Choose cohort-consistent inputs</h2>
    <ul>
      <li>Calculate CAC and monthly contribution for the same customer cohort and acquisition period.</li>
      <li>Use recognized revenue and margin rules that match your financial reporting.</li>
      <li>Separate channels when acquisition cost or customer quality differs materially.</li>
      <li>Do not subtract the same cost through both gross margin and the extra variable-cost field.</li>
    </ul>

    <h2>What the simple model leaves out</h2>
    <p>
      A single-period estimate does not model churn, annual prepayments, delayed implementation, expansion revenue, or
      the time value of money. Use it as a fast diagnostic, then build a cohort cash-flow model when those effects are
      material to a budget or hiring decision.
    </p>
  </>
);

export default function PaybackPeriodCalculatorPage() {
  return (
    <ToolPageLayout
      toolSlug="payback-period-calculator"
      title="Payback Period Calculator"
      description="Estimate how many months customer contribution takes to recover your acquisition cost."
      toolComponent={<PaybackPeriodCalculatorForm />}
      educationalContent={educationalContent}
      faqs={faqs}
      relatedToolsCategory="analytics"
      ctaTitle="Measure the behavior behind acquisition economics"
      ctaDescription="Follow conversions and retention with privacy-friendly product and web analytics."
      ctaEventLocation="payback_period_calculator_cta"
      structuredData={structuredData}
    />
  );
}
