export const searchDomains = [
  // Google and variants
  "google.com",
  "google.",

  // Bing
  "bing.com",
  "bing.",

  // Yahoo
  "yahoo.com",
  "yahoo.",
  "search.yahoo.",

  // Other global search engines
  "duckduckgo.com",
  "duck.com",
  "baidu.com",
  "baidu.",
  "yandex.com",
  "yandex.",
  "ya.ru",
  "qwant.com",
  "search.",
  "ecosia.org",
  "brave.com",
  "startpage.com",
  "searchencrypt.com",
  "searx.",
  "swisscows.com",
  "mojeek.com",
  "gibiru.com",
  "metager.org",
  "search.aol.com",
  "lycos.com",
  "wolframalpha.com",
  "ask.com",
  "dogpile.com",
  "webcrawler.com",

  // Regional search engines
  "naver.com",
  "daum.net",
  "seznam.cz",
  "coccoc.com",
  "yam.com",
  "so.com",
  "sogou.com",
  "goo.ne.jp",
  "rambler.ru",
];

export const socialDomains = [
  // Major social networks and their variants
  "facebook.com",
  "fb.com",
  "fb.me",
  "messenger.com",
  "m.facebook.com",
  "instagram.com",
  "instagram.",
  "ig.me",
  "twitter.com",
  "t.co",
  "x.com",
  "linkedin.com",
  "lnkd.in",
  "tiktok.com",
  "tiktok.",
  "vm.tiktok.com",
  "pinterest.com",
  "pinterest.",
  "pin.it",
  "reddit.com",
  "redd.it",
  "old.reddit.com",

  // Other global social platforms
  "snapchat.com",
  "snap.com",
  "youtube.com",
  "youtu.be",
  "discord.com",
  "discord.gg",
  "whatsapp.com",
  "wa.me",
  "telegram.org",
  "t.me",
  "medium.com",
  "tumblr.com",
  "tmblr.co",
  "quora.com",
  "threads.net",
  "mastodon.social",
  "mastodon.",
  "slack.com",
  "nextdoor.com",
  "clubhouse.com",
  "twitch.tv",
  "news.ycombinator.com",
  "hn.algolia.com",

  // Regional social platforms
  "wechat.com",
  "weixin.qq.com",
  "vk.com",
  "qq.com",
  "weibo.com",
  "weibo.cn",
  "line.me",
];

export const videoDomains = [
  // Major video platforms
  "youtube.com",
  "youtu.be",
  "vimeo.com",
  "twitch.tv",
  "dailymotion.com",

  // Streaming services
  "netflix.com",
  "disneyplus.com",
  "hulu.com",
  "hbomax.com",
  "peacocktv.com",
  "primevideo.com",
  "amazon.com/prime-video",
  "paramountplus.com",
  "discoveryplus.com",
  "crunchyroll.com",
  "funimation.com",
  "curiositystream.com",
  "mubi.com",

  // Video sharing
  "tiktok.com",
  "vm.tiktok.com",
  "vevo.com",
  "streamable.com",
  "bitchute.com",
  "rumble.com",
  "odysee.com",
  "lbry.tv",
  "tiktok.com",
  "reels.instagram.com",

  // Educational
  "ted.com",
  "khanacademy.org",
  "skillshare.com",
  "udemy.com",
  "masterclass.com",
  "coursera.org",
  "pluralsight.com",
  "lynda.com",
  "linkedin.com/learning",

  // Live streaming
  "facebook.com/gaming",
  "youtube.com/live",
  "kick.com",
  "caffeine.tv",

  // Regional platforms
  "bilibili.com",
  "niconico.jp",
  "vlive.tv",
  "youku.com",
  "tudou.com",
  "iqiyi.com",
];

export const shoppingDomains = [
  // Major marketplaces
  "amazon.com",
  "amazon.",
  "ebay.com",
  "ebay.",
  "etsy.com",
  "walmart.com",
  "target.com",
  "aliexpress.com",
  "wish.com",
  "shopify.com",
  "shop.app",

  // Fashion and apparel
  "asos.com",
  "zara.com",
  "forever21.com",
  "hm.com",
  "gap.com",
  "macys.com",
  "nordstrom.com",
  "net-a-porter.com",
  "farfetch.com",
  "fashionnova.com",

  // Electronics
  "bestbuy.com",
  "newegg.com",
  "bhphotovideo.com",
  "apple.com/shop",
  "samsung.com/shop",

  // Home and furniture
  "wayfair.com",
  "ikea.com",
  "homedepot.com",
  "lowes.com",
  "overstock.com",

  // Regional marketplaces
  "taobao.com",
  "jd.com",
  "rakuten.com",
  "flipkart.com",
  "lazada.com",
  "mercadolibre.com",
  "ozon.ru",
  "allegro.pl",
  "coupang.com",
  "gmarket.co.kr",

  // Grocery and food
  "instacart.com",
  "freshdirect.com",
  "ocado.com",
  "groceries.",
  "doordash.com",
  "ubereats.com",
  "grubhub.com",
  "deliveroo.com",
];

// Define sources types
export const searchSources = [
  // Major search engines
  "google",
  "bing",
  "yahoo",
  "duckduckgo",
  "baidu",
  "yandex",
  "qwant",

  // Other search engines
  "ecosia",
  "brave",
  "startpage",
  "searchencrypt",
  "swisscows",
  "mojeek",
  "gibiru",
  "metager",
  "wolframalpha",
  "ask",
  "dogpile",
  "webcrawler",
  "aol",

  // Regional search engines
  "naver",
  "daum",
  "seznam",
  "coccoc",
  "yam",
  "so",
  "sogou",
  "goo",
  "rambler",
];
export const socialSources = [
  // Major social platforms
  "facebook",
  "twitter",
  "linkedin",
  "instagram",
  "tiktok",
  "pinterest",
  "reddit",

  // Other platforms
  "snapchat",
  "youtube",
  "discord",
  "whatsapp",
  "telegram",
  "medium",
  "tumblr",
  "quora",
  "threads",
  "mastodon",
  "slack",
  "nextdoor",
  "clubhouse",
  "twitch",
  "hacker news",
  "hackernews",
  "ycombinator",

  // Shortened variants
  "fb",
  "ig",
  "pin",
  "li",
  "tw",
  "yt",

  // Regional platforms
  "wechat",
  "weixin",
  "vk",
  "qq",
  "weibo",
  "line",
  "kakao",
];
export const videoSources = [
  // Major video platforms
  "youtube",
  "vimeo",
  "twitch",
  "dailymotion",
  "tiktok",

  // Streaming services
  "disneyplus",
  "netflix",
  "hulu",
  "hbomax",
  "peacock",
  "prime video",
  "paramount+",
  "discovery+",
  "crunchyroll",
  "funimation",
  "curiositystream",
  "mubi",

  // Video sharing
  "vevo",
  "streamable",
  "bitchute",
  "rumble",
  "odysee",
  "lbry",
  "reels",

  // Educational
  "ted",
  "khanacademy",
  "skillshare",
  "udemy",
  "masterclass",
  "coursera",
  "pluralsight",
  "lynda",

  // Live streaming
  "kick",
  "caffeine",

  // Regional platforms
  "bilibili",
  "niconico",
  "vlive",
  "youku",
  "tudou",
  "iqiyi",
];
export const shoppingSources = [
  // Major marketplaces
  "amazon",
  "ebay",
  "etsy",
  "shopify",
  "walmart",
  "target",
  "aliexpress",
  "wish",
  "shop",
  "store",
  "shopping",

  // Fashion and apparel
  "asos",
  "zara",
  "forever21",
  "hm",
  "gap",
  "macys",
  "nordstrom",
  "net-a-porter",
  "farfetch",
  "fashionnova",

  // Electronics
  "bestbuy",
  "newegg",
  "bhphotovideo",
  "apple",
  "samsung",

  // Home and furniture
  "wayfair",
  "ikea",
  "homedepot",
  "lowes",
  "overstock",

  // Regional marketplaces
  "taobao",
  "jd",
  "rakuten",
  "flipkart",
  "lazada",
  "mercadolibre",
  "ozon",
  "allegro",
  "coupang",
  "gmarket",

  // Grocery and food
  "instacart",
  "freshdirect",
  "ocado",
  "groceries",
  "doordash",
  "ubereats",
  "grubhub",
  "deliveroo",
];
export const emailSources = [
  "email",
  "e_mail",
  "e-mail",
  "mail",
  "newsletter",
  "mailchimp",
  "campaign-archive",
  "sendgrid",
  "mailgun",
  "constantcontact",
  "klaviyo",
  "hubspot",
  "marketo",
  "brevo",
  "sendinblue",
  "getresponse",
  "activecampaign",
  "mailerlite",
  "convertkit",
  "drip",
  "gmail",
  "yahoo",
  "outlook",
  "hotmail",
  "list",
  "blast",
  "campaign",
];
export const smsSources = [
  "sms",
  "text",
  "twilio",
  "message",
  "whatsapp",
  "viber",
  "line",
  "imessage",
];

// Medium types
export const socialMediums = [
  "sm",
  "social-media",
  "social-network",
  "social",
  "community",
  "forum",
  "organic-social",
  "feed",
  "share",
  "repost",
  "tweet",
  "post",
  "update",
  "engagement",
  "ugc",
  "user-generated",
  "social_post",
];

export const videoMediums = [
  "video",
  "youtube",
  "vimeo",
  "streaming",
  "live",
  "tv",
  "ott",
  "broadcast",
  "clip",
  "trailer",
  "episode",
  "series",
  "documentary",
  "film",
  "movie",
  "animation",
  "video_ad",
  "pre-roll",
  "mid-roll",
  "post-roll",
];

export const displayMediums = [
  "display",
  "interstitial",
  "banner",
  "ad",
  "advert",
  "advertisement",
  "rich-media",
  "popup",
  "popunder",
  "overlay",
  "expandable",
  "floating",
  "skin",
  "wallpaper",
  "native",
  "programmatic",
  "dsp",
  "retargeting",
  "remarketing",
  "impression",
];

export const affiliateMediums = [
  "affiliate",
  "aff",
  "partner",
  "partnership",
  "commission",
  "rev-share",
  "performance",
  "cpa",
  "lead-gen",
  "lead-generation",
];

export const referralMediums = [
  "referral",
  "link",
  "app",
  "invite",
  "recommendation",
  "advocate",
  "refer-a-friend",
  "share",
  "web",
  "embed",
  "backlink",
  "qr",
  "qr-code",
  "deeplink",
  "vanity-url",
];

export const emailMediums = [
  "email",
  "e_mail",
  "e-mail",
  "mail",
  "newsletter",
  "digest",
  "bulletin",
  "marketing_email",
  "promotional",
  "transactional",
  "notification_email",
  "alert",
  "confirmation",
  "update",
  "news",
];

export const pushMediums = [
  "push",
  "notification",
  "mobile",
  "app-notification",
  "web-notification",
  "browser-notification",
  "alert",
  "toast",
  "prompt",
  "pwa",
  "install",
];

export const audioMediums = [
  "audio",
  "podcast",
  "radio",
  "broadcast",
  "streaming",
  "music",
  "playlist",
  "episode",
  "show",
  "airplay",
  "song",
  "track",
  "voice",
  "audio_ad",
  "spot",
  "jingle",
  "commercial",
];
