/**
 * Bot user-agent patterns, vendored from the `isbot` package (Unlicense / public domain)
 * and annotated with categories.
 *
 * Source: https://github.com/omrilotan/isbot/blob/main/src/patterns.json
 *
 * Categories drive policy in trackEvent: some bot categories are dropped silently,
 * others can be counted and tagged. To re-sync against upstream, copy patterns.json
 * verbatim and reapply categories from this file by matching the `pattern` string.
 *
 * IMPORTANT: order matters. classifyUA returns the FIRST matching pattern, so more
 * specific patterns must appear before generic substring matches. The upstream
 * ordering already mostly satisfies this (anchored patterns first, generic
 * substrings last); preserve it on sync.
 */

export type BotCategory =
  | "search" // search engine crawlers (Googlebot, Bingbot, DuckDuckBot, etc.)
  | "ai" // AI training / retrieval / agent crawlers
  | "social" // social link-preview bots (facebookexternalhit, Twitterbot, Slackbot)
  | "monitoring" // uptime / synthetic / performance monitoring
  | "seo" // SEO crawlers (Ahrefs, SEMrush, Moz, Nutch, etc.)
  | "security" // security scanners (Burp, ClamAV, etc.)
  | "framework" // HTTP libraries / scripting clients (curl, python-requests, etc.)
  | "headless" // headless browsers and browser automation
  | "generic"; // matched a bot-ish pattern but uncategorized

export interface BotPattern {
  /** Regex source string. Compiled with the `i` flag. */
  pattern: string;
  category: BotCategory;
}

export const BOT_PATTERNS: BotPattern[] = [
  { pattern: " daum[ /]", category: "search" },
  { pattern: " deusu/", category: "search" },
  { pattern: "(?:^|[^g])news(?!sapphire)", category: "generic" },
  { pattern: "(?<! (?:channel/|google/))google(?!(app|/google| pixel))", category: "search" },
  { pattern: "(?<! cu)bots?(?:\\b|_)", category: "generic" },
  { pattern: "(?<!(?:lib))http", category: "framework" },
  { pattern: "(?<!cam)scan", category: "security" },
  { pattern: "24x7", category: "monitoring" },
  { pattern: "@[a-z][\\w-]+\\.", category: "generic" },
  { pattern: "\\(\\)", category: "generic" },
  { pattern: "\\.com\\b", category: "generic" },
  { pattern: "\\b\\w+\\.ai", category: "ai" },
  { pattern: "\\bcursor/", category: "ai" },
  { pattern: "\\bmanus-user/", category: "ai" },
  { pattern: "\\bort/", category: "generic" },
  { pattern: "\\bperl\\b", category: "framework" },
  { pattern: "\\bplaywright\\b", category: "headless" },
  { pattern: "\\bsecurityheaders\\b", category: "monitoring" },
  { pattern: "\\bselenium\\b", category: "headless" },
  { pattern: "\\btime/", category: "generic" },
  { pattern: "\\|", category: "generic" },
  { pattern: "^[\\w \\.\\-\\(?:\\):%]+(?:/v?\\d+(?:\\.\\d+)?(?:\\.\\d{1,10})*?)?(?:,|$)", category: "generic" },
  { pattern: "^[\\w\\-]+/[\\w]+$", category: "generic" },
  { pattern: "^[^ ]{50,}$", category: "generic" },
  { pattern: "^\\d+\\b", category: "generic" },
  { pattern: "^\\W", category: "generic" },
  { pattern: "^\\w*search\\b", category: "search" },
  { pattern: "^\\w+/[\\w\\(\\)]*$", category: "generic" },
  { pattern: "^\\w+/\\d\\.\\d\\s\\([\\w@]+\\)$", category: "generic" },
  { pattern: "^active", category: "generic" },
  { pattern: "^ad muncher", category: "generic" },
  { pattern: "^amaya", category: "generic" },
  { pattern: "^apache/", category: "framework" },
  { pattern: "^avsdevicesdk/", category: "generic" },
  { pattern: "^azure", category: "framework" },
  { pattern: "^biglotron", category: "seo" },
  { pattern: "^bot", category: "generic" },
  { pattern: "^bw/", category: "generic" },
  { pattern: "^clamav[ /]", category: "security" },
  { pattern: "^claude-code/", category: "ai" },
  { pattern: "^client/", category: "generic" },
  { pattern: "^cobweb/", category: "seo" },
  { pattern: "^custom", category: "generic" },
  { pattern: "^ddg[_-]android", category: "search" },
  { pattern: "^discourse", category: "generic" },
  { pattern: "^dispatch/\\d", category: "generic" },
  { pattern: "^downcast/", category: "generic" },
  { pattern: "^duckduckgo", category: "search" },
  { pattern: "^email", category: "generic" },
  { pattern: "^facebook", category: "social" },
  { pattern: "^getright/", category: "generic" },
  { pattern: "^gozilla/", category: "generic" },
  { pattern: "^hobbit", category: "generic" },
  { pattern: "^hotzonu", category: "generic" },
  { pattern: "^hwcdn/", category: "generic" },
  { pattern: "^igetter/", category: "generic" },
  { pattern: "^jeode/", category: "framework" },
  { pattern: "^jetty/", category: "framework" },
  { pattern: "^jigsaw", category: "framework" },
  { pattern: "^microsoft bits", category: "framework" },
  { pattern: "^movabletype", category: "generic" },
  { pattern: "^mozilla/\\d\\.\\d\\s[\\w\\.-]+$", category: "generic" },
  { pattern: "^mozilla/\\d\\.\\d\\s\\((?:compatible;)?(?:\\s?[\\w\\d-.]+\\/\\d+\\.\\d+)?\\)$", category: "generic" },
  { pattern: "^navermailapp", category: "generic" },
  { pattern: "^netsurf", category: "generic" },
  { pattern: "^offline", category: "generic" },
  { pattern: "^openai/", category: "ai" },
  { pattern: "^owler", category: "seo" },
  { pattern: "^php", category: "framework" },
  { pattern: "^postman", category: "framework" },
  { pattern: "^python", category: "framework" },
  { pattern: "^rank", category: "seo" },
  { pattern: "^read", category: "generic" },
  { pattern: "^reed", category: "generic" },
  { pattern: "^rest", category: "framework" },
  { pattern: "^rss", category: "generic" },
  { pattern: "^snapchat", category: "social" },
  { pattern: "^space bison", category: "generic" },
  { pattern: "^svn", category: "framework" },
  { pattern: "^swcd ", category: "generic" },
  { pattern: "^taringa", category: "social" },
  { pattern: "^thumbor/", category: "framework" },
  { pattern: "^track", category: "generic" },
  { pattern: "^w3c", category: "generic" },
  { pattern: "^webbandit/", category: "generic" },
  { pattern: "^webcopier", category: "generic" },
  { pattern: "^wget", category: "framework" },
  { pattern: "^whatsapp", category: "social" },
  { pattern: "^wordpress", category: "generic" },
  { pattern: "^xenu link sleuth", category: "seo" },
  { pattern: "^yahoo", category: "search" },
  { pattern: "^yandex", category: "search" },
  { pattern: "^zdm/\\d", category: "generic" },
  { pattern: "^zoom marketplace/", category: "generic" },
  { pattern: "advisor", category: "generic" },
  { pattern: "agent\\b", category: "generic" },
  { pattern: "analyzer", category: "monitoring" },
  { pattern: "archive", category: "generic" },
  { pattern: "ask jeeves/teoma", category: "search" },
  { pattern: "audit", category: "monitoring" },
  { pattern: "bit\\.ly/", category: "generic" },
  { pattern: "bluecoat drtr", category: "generic" },
  { pattern: "browsex", category: "generic" },
  { pattern: "burpcollaborator", category: "security" },
  { pattern: "capture", category: "generic" },
  { pattern: "catch", category: "generic" },
  { pattern: "check\\b", category: "monitoring" },
  { pattern: "checker", category: "monitoring" },
  { pattern: "chrome-lighthouse", category: "monitoring" },
  { pattern: "chromeframe", category: "generic" },
  { pattern: "classifier", category: "generic" },
  { pattern: "cloudflare", category: "generic" },
  { pattern: "convertify", category: "generic" },
  { pattern: "crawl", category: "generic" },
  { pattern: "cypress/", category: "headless" },
  { pattern: "dareboost", category: "monitoring" },
  { pattern: "datanyze", category: "seo" },
  { pattern: "dejaclick", category: "monitoring" },
  { pattern: "detect", category: "monitoring" },
  { pattern: "dmbrowser", category: "generic" },
  { pattern: "download", category: "generic" },
  { pattern: "exaleadcloudview", category: "search" },
  { pattern: "feed", category: "generic" },
  { pattern: "fetcher", category: "generic" },
  { pattern: "firephp", category: "framework" },
  { pattern: "functionize", category: "monitoring" },
  { pattern: "grab", category: "generic" },
  { pattern: "headless", category: "headless" },
  { pattern: "httrack", category: "generic" },
  { pattern: "hubspot marketing grader", category: "monitoring" },
  { pattern: "ibisbrowser", category: "generic" },
  { pattern: "infrawatch", category: "monitoring" },
  { pattern: "insight", category: "monitoring" },
  { pattern: "inspect", category: "monitoring" },
  { pattern: "iplabel", category: "monitoring" },
  { pattern: "java(?!;)", category: "framework" },
  { pattern: "library", category: "generic" },
  { pattern: "linkcheck", category: "seo" },
  { pattern: "mail\\.ru/", category: "search" },
  { pattern: "manager", category: "generic" },
  { pattern: "measure", category: "monitoring" },
  { pattern: "monitor\\b", category: "monitoring" },
  { pattern: "neustar wpm", category: "monitoring" },
  { pattern: "node\\b", category: "framework" },
  { pattern: "nutch", category: "seo" },
  { pattern: "offbyone", category: "generic" },
  { pattern: "onetrust", category: "generic" },
  { pattern: "optimize", category: "monitoring" },
  { pattern: "pageburst", category: "monitoring" },
  { pattern: "pagespeed", category: "monitoring" },
  { pattern: "parser", category: "framework" },
  { pattern: "phantomjs", category: "headless" },
  { pattern: "pingdom", category: "monitoring" },
  { pattern: "powermarks", category: "generic" },
  { pattern: "preview", category: "social" },
  { pattern: "proxy", category: "generic" },
  { pattern: "ptst[ /]\\d", category: "monitoring" },
  { pattern: "retriever", category: "generic" },
  { pattern: "rexx;", category: "framework" },
  { pattern: "rigor", category: "monitoring" },
  { pattern: "rss\\b", category: "generic" },
  { pattern: "scrape", category: "generic" },
  { pattern: "server", category: "generic" },
  { pattern: "sogou", category: "search" },
  { pattern: "sparkler/", category: "generic" },
  { pattern: "speedcurve", category: "monitoring" },
  { pattern: "spider", category: "generic" },
  { pattern: "splash", category: "headless" },
  { pattern: "statuscake", category: "monitoring" },
  { pattern: "supercleaner", category: "generic" },
  { pattern: "synapse", category: "generic" },
  { pattern: "synthetic", category: "monitoring" },
  { pattern: "tools", category: "generic" },
  { pattern: "torrent", category: "generic" },
  { pattern: "transcoder", category: "generic" },
  { pattern: "url", category: "generic" },
  { pattern: "validator", category: "monitoring" },
  { pattern: "virtuoso", category: "framework" },
  { pattern: "wappalyzer", category: "seo" },
  { pattern: "webglance", category: "generic" },
  { pattern: "webkit2png", category: "headless" },
  { pattern: "whatcms/", category: "seo" },
  { pattern: "xtate/", category: "generic" },
];

/**
 * Additional and priority AI / social / monitoring identifiers. Some duplicate
 * upstream patterns intentionally so they win before broad generic rules like
 * "(?<! cu)bots?" and "(?<!(?:lib))http".
 */
export const EXTRA_BOT_PATTERNS: BotPattern[] = [
  // AI training / retrieval crawlers
  { pattern: "^openai/", category: "ai" },
  { pattern: "^claude-code/", category: "ai" },
  { pattern: "\\bgptbot\\b", category: "ai" },
  { pattern: "\\boai-searchbot\\b", category: "ai" },
  { pattern: "\\bchatgpt-user\\b", category: "ai" },
  { pattern: "\\bclaudebot\\b", category: "ai" },
  { pattern: "\\bclaude-user\\b", category: "ai" },
  { pattern: "\\bclaude-searchbot\\b", category: "ai" },
  { pattern: "\\bperplexitybot\\b", category: "ai" },
  { pattern: "\\bperplexity-user\\b", category: "ai" },
  { pattern: "\\bbytespider\\b", category: "ai" },
  { pattern: "\\bccbot\\b", category: "ai" },
  { pattern: "\\bgoogle-extended\\b", category: "ai" },
  { pattern: "\\bmeta-externalagent\\b", category: "ai" },
  { pattern: "\\bmeta-externalfetcher\\b", category: "ai" },
  { pattern: "\\bdiffbot\\b", category: "ai" },
  { pattern: "\\bcohere-ai\\b", category: "ai" },
  { pattern: "\\bapplebot-extended\\b", category: "ai" },
  { pattern: "\\bamazonbot\\b", category: "ai" },
  { pattern: "\\bmistralai-user\\b", category: "ai" },
  { pattern: "\\bgrokbot\\b", category: "ai" },
  { pattern: "\\byouchat\\b", category: "ai" },

  // Search crawlers whose names can be swallowed by generic "*bot*" rules
  { pattern: "yandexbot", category: "search" },
  { pattern: "duckduckgo", category: "search" },
  { pattern: "slurp", category: "search" },

  // Social link previewers not caught by upstream
  { pattern: "facebookexternalhit", category: "social" },
  { pattern: "facebot", category: "social" },
  { pattern: "twitterbot", category: "social" },
  { pattern: "slackbot", category: "social" },
  { pattern: "discordbot", category: "social" },
  { pattern: "linkedinbot", category: "social" },
  { pattern: "telegrambot", category: "social" },
  { pattern: "skypeuripreview", category: "social" },
  { pattern: "redditbot", category: "social" },
  { pattern: "pinterestbot", category: "social" },
  { pattern: "embedly", category: "social" },

  // SEO crawlers commonly seen in the wild
  { pattern: "ahrefsbot", category: "seo" },
  { pattern: "semrushbot", category: "seo" },
  { pattern: "mj12bot", category: "seo" },
  { pattern: "dotbot", category: "seo" },
  { pattern: "rogerbot", category: "seo" },
  { pattern: "screaming frog seo spider", category: "seo" },
  { pattern: "serpstatbot", category: "seo" },

  // Scripted clients and browser automation
  { pattern: "python-requests", category: "framework" },
  { pattern: "curl/", category: "framework" },
  { pattern: "^wget", category: "framework" },
  { pattern: "postmanruntime", category: "framework" },
  { pattern: "apache-httpclient", category: "framework" },
  { pattern: "headlesschrome", category: "headless" },
  { pattern: "phantomjs", category: "headless" },
  { pattern: "\\bplaywright\\b", category: "headless" },
  { pattern: "\\bselenium\\b", category: "headless" },

  // Monitoring services
  { pattern: "pingdom", category: "monitoring" },
  { pattern: "uptimerobot", category: "monitoring" },
  { pattern: "datadog", category: "monitoring" },
  { pattern: "newrelic", category: "monitoring" },
  { pattern: "site24x7", category: "monitoring" },
  { pattern: "betteruptime", category: "monitoring" },
  { pattern: "statuscake", category: "monitoring" },
  { pattern: "chrome-lighthouse", category: "monitoring" },
];

// EXTRA patterns come first so explicit named bots (ClaudeBot, AhrefsBot, etc.)
// get their specific category before the upstream generic substring matches
// (e.g. the "(?<! cu)bots?" rule) catch them as "generic".
export const ALL_BOT_PATTERNS: BotPattern[] = [...EXTRA_BOT_PATTERNS, ...BOT_PATTERNS];
